name: Execução dos testes de integração

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuração das varíaveis de ambiente
        run: |
          echo "TEST_USER=${{ secrets.TEST_USER }}" >> .env
          echo "TEST_HOST=${{ secrets.TEST_HOST }}" >> .env
          echo "TEST_DATABASE=${{ secrets.TEST_DATABASE }}" >> .env
          echo "TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}" >> .env
          echo "TEST_PORT=${{ secrets.TEST_PORT }}" >> .env

      
      - name: Install dependences
        run: yarn
      
      - name: Run tests
        run: yarn test
      
      
