name: Execução dos testes de integração

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependences
        run: yarn

      - name: Configure .env
        env:
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_HOST: ${{ secrets.TEST_HOST }}
          TEST_DATABASE: ${{ secrets.TEST_DATABASE }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_PORT: ${{ secrets.TEST_PORT }}
        run: |
          echo $TEST_PASSWORD | psql -U "$TEST_USER" -h "$TEST_HOST" -d "$TEST_DATABASE" -f create_tables.sql
      
      - name: Run tests
        run: yarn test
